#!/bin/bash

# $IMAGE_NAME var is injected into the build so the tag is correct.

echo "Build hook running"
docker build --build-arg BUILD_DATE="$(shell date --iso-8601=seconds)" \
             --build-arg VCS_REF="$(shell git rev-parse --short HEAD)"	  \
             --build-arg VCS_URL="$(shell git config --get remote.origin.url)" \
             -t $IMAGE_NAME .
